### ISSUE TITLE
Crash on linux systems

### ISSUE THREAD

**Issue by HyCraftHD** [HyCraftHD/Worldgeneration-Profiler#3]
It seems, that the bytecode classes could not be loaded correctly to vm. The path may be wrong for linux systems, while it is working correctly for windows.

**Comment by HyCraftHD** [comment]
#2

**Comment by HyCraftHD** [comment]
`[03:35:44] [Server thread/INFO] [Worldgeneration Profiler Plugin]: Trying to patch class net.minecraftforge.fml.common.registry.GameRegistry
[03:35:44] [Server thread/INFO] [Worldgeneration Profiler Plugin]: Using /1.9-1.11-obf.byte to load class.
[03:35:44] [Server thread/ERROR] [Worldgeneration Profiler Plugin]: CustomWorldGenerator class could not be loaded to classloader.
java.lang.ClassNotFoundException: net.hycrafthd.worldgenerationprofiler.generation.CustomWorldGenerator
at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?]
at net.hycrafthd.worldgenerationprofiler.asm.visitor.VisitorGameRegistry.insert(VisitorGameRegistry.java:65) [worldgenerationprofiler-v1.1.0(1).jar:1.1.0]
at net.hycrafthd.worldgenerationprofiler.asm.visitor.VisitorGameRegistry.transform(VisitorGameRegistry.java:41) [worldgenerationprofiler-v1.1.0(1).jar:1.1.0]
at net.hycrafthd.worldgenerationprofiler.asm.VisitorHelper.transform(VisitorHelper.java:33) [worldgenerationprofiler-v1.1.0(1).jar:1.1.0]
at net.hycrafthd.worldgenerationprofiler.asm.transformer.Transformer.transform(Transformer.java:38) [worldgenerationprofiler-v1.1.0(1).jar:1.1.0]
at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:249) [ASMTransformerWrapper$TransformerWrapper.class:?]
at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) [launchwrapper-1.12.jar:?]
at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) [launchwrapper-1.12.jar:?]
at java.lang.ClassLoader.loadClass(ClassLoader.java:424) [?:1.8.0_101]
at java.lang.ClassLoader.loadClass(ClassLoader.java:357) [?:1.8.0_101]
at com.github.atomicblom.weirdinggadget.registration.Registration.registerBlocks(Registration.java:29) [Registration.class:?]
at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_16_Registration_registerBlocks_Register.invoke(.dynamic) [?:?]
at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) [ASMEventHandler.class:?]
at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:144) [EventBus$1.class:?]
at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185) [EventBus.class:?]
at net.minecraftforge.fml.common.registry.PersistentRegistryManager.fireRegistryEvent(PersistentRegistryManager.java:98) [PersistentRegistryManager.class:?]
at net.minecraftforge.fml.common.registry.PersistentRegistryManager.fireRegistryEvents(PersistentRegistryManager.java:85) [PersistentRegistryManager.class:?]
at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:622) [Loader.class:?]
at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:99) [FMLServerHandler.class:?]
at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:328) [FMLCommonHandler.class:?]
at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:121) [ld.class:?]
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:431) [MinecraftServer.class:?]
at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]
Caused by: net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerException: Exception in class transformer net.hycrafthd.worldgenerationprofiler.asm.transformer.Transformer@1c938e27 from coremod Worldgeneration Profiler Plugin
at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:253) ~[ftbserver.jar:?]
at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) ~[launchwrapper-1.12.jar:?]
at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) ~[launchwrapper-1.12.jar:?]
... 22 more
Caused by: java.lang.NoClassDefFoundError: org/apache/commons/compress/utils/IOUtils
at net.hycrafthd.worldgenerationprofiler.asm.transformer.Transformer.transform(Transformer.java:32) ~[worldgenerationprofiler-v1.1.0(1).jar:1.1.0]
at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:249) ~[ftbserver.jar:?]
at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) ~[launchwrapper-1.12.jar:?]
at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) ~[launchwrapper-1.12.jar:?]
... 22 more
Caused by: java.lang.ClassNotFoundException: org.apache.commons.compress.utils.IOUtils
at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[?:1.8.0_101]
at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_101]
at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331) ~[?:1.8.0_101]
at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_101]
at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:106) ~[launchwrapper-1.12.jar:?]
at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_101]
at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_101]
at net.hycrafthd.worldgenerationprofiler.asm.transformer.Transformer.transform(Transformer.java:32) ~[worldgenerationprofiler-v1.1.0(1).jar:1.1.0]
at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:249) ~[ftbserver.jar:?]
at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) ~[launchwrapper-1.12.jar:?]
at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) ~[launchwrapper-1.12.jar:?]
... 22 more
[03:35:44] [Server thread/INFO] [FML]: Java has been asked to exit (code 0) by net.minecraftforge.fml.common.FMLCommonHandler.exitJava(FMLCommonHandler.java:656).
[03:35:44] [Server thread/INFO] [FML]: This is an abortive exit and could cause world corruption or other things
[03:35:44] [Server thread/INFO] [FML]: If this was an unexpected exit, use -Dfml.debugExit=true as a JVM argument to find out where it was called
SERVER SHUT DOWN`

**Comment by HyCraftHD** [comment]
https://stackoverflow.com/questions/21658061/getclass-getresourceresourcepath-valid-on-windows-null-on-linux

**Comment by HyCraftHD** [comment]
The used class IoUtils from apache is not loaded on linux systems. Therefore this will trigger the crash.
