### ISSUE TITLE
crash with spongeForge

### ISSUE THREAD

**Issue by Bucky420** [HyCraftHD/Worldgeneration-Profiler#6]
`6:13:10] [main/INFO] [Worldgeneration Profiler Plugin]: Using 1.12-obf.byte for class.
[16:13:10] [main/INFO] [Worldgeneration Profiler Plugin]: CustomWorldGenerator loaded in vm successfully for V1_12 (net.hycrafthd.worldgenerationprofiler.generation.CustomWorldGenerator)
[16:13:10] [main/INFO] [Worldgeneration Profiler Plugin]: Patched class successfully net.minecraftforge.fml.common.registry.GameRegistry
[16:13:10] [main/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transformClassBytes:519]: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Redirector redirect$onGenerateWorld$zzd000(Lnet/minecraftforge/fml/common/IWorldGenerator;Ljava/util/Random;IILnet/minecraft/world/World;Lnet/minecraft/world/gen/IChunkGenerator;Lnet/minecraft/world/chunk/IChunkProvider;)V in mixins.forge.preinit.json:fml.common.registry.MixinGameRegistry failed injection check, (0/1) succeeded. Using refmap mixins.forge.refmap.json
[16:13:10] [main/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transformClassBytes:519]:    at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:290)
[16:13:10] [main/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transformClassBytes:519]:    at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1203)
[16:13:10] [main/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transformClassBytes:519]:    at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:938)
[16:13:10] [main/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transformClassBytes:519]:    at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:322)
[16:13:10] [main/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transformClassBytes:519]:    at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:280)
[16:13:10] [main/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transformClassBytes:519]:    at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:353)
[16:13:10] [main/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transformClassBytes:519]:    at org.spongepowered.asm.mixin.transformer.MixinTransformer.apply(Mixin`

**Comment by HyCraftHD** [comment]
Spongeforge is not supported.
